version: '3.7'
services:
  php73:
    image: vvvroom/laravel:7.3
    build:
      context: .
      dockerfile: php73.Dockerfile
    volumes:
      - ./laravel:/var/www/app
      - composer_cache:/root/.composer/cache
    ports:
      - 7100:443
  php74:
    image: vvvroom/laravel:7.4
    build:
      context: .
      dockerfile: php74.Dockerfile
    volumes:
      - ./laravel:/var/www/app
      - composer_cache:/root/.composer/cache
    ports:
      - 7101:443
volumes:
  composer_cache:
      driver: local
